#include <catch2/catch_test_macros.hpp>

#include "testhelper.h"
#include "solutions/Day07.h"
using namespace aoc::year2025;

/** Tests for https://adventofcode.com/2025/day/7 */

TEST_CASE ("Day07 for example input 1", "[example]") {
    const auto exampleInput1 = R"(.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
)";

    Day07 day{};
    testPart1(day, exampleInput1, 21);
    testPart2(day, exampleInput1, 40);
}

TEST_CASE ("Day07 for puzzle input", "[puzzle]") {
    Day07 day{};
    const std::string input = loadPuzzleInput(day);
    //testPart1(day, input, 1537);
    // testPart2(day, input, "not_implemented");
}

